spring:
  application:
    name: eureka-server
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka
    fetch-registry: false
    register-with-eureka: false